name = "astro-blog-comments"
main = "src/worker.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGINS = "https://blog.seso.icu"

[durable_objects]
bindings = []

[[d1_databases]]
binding = "DB"
database_name = "astro-blog-comments-db"
database_id = "d0dd86fc-8853-4a1d-a366-e0b6777b3205"

